version: "3.8"
services:
  grocery-app:
    build: .
    container_name: grocery-container
    ports:
      - "8080:8080"
    volumes:
      - .:/app # Map the current directory to /app inside the container
      - /app/node_modules # Prevent overwriting node_modules
    working_dir: /app # Set the working directory
    command: npm start # Use the start script that runs nodemon
