# services:
#   img:
#     build: .
#     container_name: grocerry-container
#     ports:
#       - "8080:8080"

services:
  img:
    build: .
    container_name: grocerry-container
    ports:
      - "8080:8080"
    volumes:
      - .:/app # Map the current directory to /app in the container
      - /app/node_modules # Prevent overwriting node_modules
    working_dir: /app # Set the working directory to the root of your project
    command: nodemon index.js # Use nodemon to watch changes in index.js